language: node.js

node_js:
  - 16

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $MY_CLOUD_VUE_TRAVIS_CI
  keep_history: true
  local_dir: dist
  on:
    branch: main
  target_branch: gh-pages
